### ISSUE TITLE
Multiple materials mess with node creation

### ISSUE THREAD

**Issue by General-101** [Project-Cartographer/DaeConverter#1]
Multiple materials seem to cause nodes to get added in weird ways. What should have been node index 0 for a vertice was node 7 for example. Example model with this issue provided below.

https://mega.nz/#!t58gmAjb!n0Nwf9xD5n1HBClSX6R4SnGcTe8hdXEutD0qKhV9kuw

**Comment by Himanshu-01** [comment]
Assimp actually breaks the mesh into smaller meshes depending upon materials and therefore i have to add each submesh as an independent mesh(having its own node_map list but they do refer to the orginal nodes).
Does this break the model?

**Comment by General-101** [comment]
It breaks skinned models due to more node maps than it should have.

**Comment by Himanshu-01** [comment]
Added a logic to prevent redundancy of node_maps
