### ISSUE TITLE
DAE converter crashing when compiling a model

### ISSUE THREAD

**Issue by General-101** [Project-Cartographer/DaeConverter#3]
As the title says. At the moment it seems to be related to weights but I can't say for certain. Model that gives this issue provided below.

https://mega.nz/#!0scz3AZa!CqLX3oNPFyAwG4VATgNQanN3rZqufZxrqIjWwA6S4mM

Event viewer log below

https://pastebin.com/aBv67Bqs

For clarification this is the elite model I pinged you with on Discord a while back. This issue is just here for the record.

**Comment by Himanshu-01** [comment]
This was an error on Assimp importer's part.
String to value conversion error.
here it is
https://ibb.co/kO0fgo
You gonna have to manually fix this as this is mistake caused by the exporter.
